// Real-scene browser evidence. Fixed BEFORE camera definitions are reused for AFTER.
// Software renderer metrics are geometry proxies, never target-GPU FPS evidence.
import {execFileSync} from 'node:child_process';
import {mkdirSync,writeFileSync,readFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const args=process.argv.slice(2);const arg=(n,d)=>args.includes(n)?args[args.indexOf(n)+1]:d;
const phase=arg('--phase','before'),base=arg('--base','http://127.0.0.1:4193');
const out=resolve(arg('--out-dir','outputs/driving-priorities-20260930'));mkdirSync(out,{recursive:true});
const run=(...a)=>execFileSync('agent-browser',['--session','driving',...a],{encoding:'utf8',maxBuffer:16e6,timeout:180000}).trim();
const evaluate=(js)=>{let r=JSON.parse(run('eval',`JSON.stringify(${js})`));return typeof r==='string'?JSON.parse(r):r;};
run('open',base+'/?player=0');run('wait','--fn','!!window.__game?.roads && !!window.__game?.water');
const report=evaluate(`(()=>{const g=window.__game,h=g.terrainHeightAt;const stats={};const water=[];for(const s of g.roads.stations()){const {x,z,dx,dz}=s;if(x<50||z<50||x>5950||z>5950)continue;const c={...s,height:h(x,z),crossSlope:(h(x-dz*2,z+dx*2)-h(x+dz*2,z-dx*2))/4,longitudinalSlope:(h(x+dx,z+dz)-h(x-dx,z-dz))/2,slopeDerivative:(h(x+dx,z+dz)-2*h(x,z)+h(x-dx,z-dz))};let k=stats[s.class]??={count:0,worstCross:null,worstDerivative:null};k.count++;if(!k.worstCross||Math.abs(c.crossSlope)>Math.abs(k.worstCross.crossSlope))k.worstCross=c;if(!k.worstDerivative||Math.abs(c.slopeDerivative)>Math.abs(k.worstDerivative.slopeDerivative))k.worstDerivative=c;let dep=g.water.depthAt(x,z);if(dep>0)water.push({...c,depth:dep});}return {phase:${JSON.stringify(phase)},terrainDiagnostics:stats,waterCrossings:water,perf:g.perf(),renderer:'Chrome headless software; FPS excluded from GPU claims',note:'Terrain finite differences at real road stations: cross slope 4m span, longitudinal 2m span, second derivative 1m spacing. Separate road sampler metrics supplied by road harness.'};})()`);
report.rendererObserved=evaluate(`(()=>{const c=document.querySelector('canvas');const gl=c.getContext('webgl2')||c.getContext('webgl');const d=gl?.getExtension('WEBGL_debug_renderer_info');return d?gl.getParameter(d.UNMASKED_RENDERER_WEBGL):gl?.getParameter(gl.RENDERER);})()`);const definitionFile=resolve(out,'cameras.json');let cameras;
if(phase==='before'||!existsSync(definitionFile)){const points=[report.terrainDiagnostics.ROAD.worstCross,report.terrainDiagnostics.ROAD.worstDerivative,report.terrainDiagnostics.TRACK.worstCross,report.terrainDiagnostics.PATH.worstDerivative];const cross=report.waterCrossings.filter(s=>s.class==='ROAD'&&s.x>2500&&s.x<3500&&s.z>3000&&s.z<3800);if(cross.length)points.push(cross[0]);points.push({x:3176,z:3450,height:evaluate('window.__game.terrainHeightAt(3176,3450)')});cameras=points.map((s,i)=>({name:['road_cross_slope','road_slope_change','track_cross_slope','path_slope_change','road_over_river','real_ford'][i],point:s,query:{px:s.x-24,py:s.height+13,pz:s.z-24,tx:s.x,ty:s.height,tz:s.z,vx:s.x,vz:s.z,vyaw:Math.atan2(s.dx??0,s.dz??1),player:0}}));writeFileSync(definitionFile,JSON.stringify(cameras,null,2));}else cameras=JSON.parse(readFileSync(definitionFile,'utf8'));
report.views=[];for(const c of cameras){run('open',base+'/?'+new URLSearchParams(c.query));run('wait','--fn','!!window.__game?.roads && !!window.__game?.water');run('wait','2200');const actual=evaluate(`(()=>{const g=window.__game,t=g.vehicle?.telemetry()??null;return {point:${JSON.stringify(c.point)},terrainHeight:g.terrainHeightAt(${c.point.x},${c.point.z}),depth:g.water.depthAt(${c.point.x},${c.point.z}),waterSurfaceY:g.water.surfaceHeightAt?.(${c.point.x},${c.point.z})??null,contactDepth:g.water.contactDepthAt?.(${c.point.x},${c.point.z})??null,roadSurface:g.roads.sampleAt?.(${c.point.x},${c.point.z})??null,telemetry:t,water:g.water.estadoAgua(),runtimeSurface:g.runtime().surface,perf:g.perf()};})()`);run('screenshot',resolve(out,phase+'_'+c.name+'.png'));report.views.push({name:c.name,...actual});console.log(phase,c.name,actual.depth,actual.perf.drawCalls);}
writeFileSync(resolve(out,phase+'_report.json'),JSON.stringify(report,null,2));console.log(resolve(out,phase+'_report.json'));
