import assert from 'node:assert/strict';
import { build } from 'esbuild';
const result=await build({entryPoints:['src/runtime/vehicle-impact.ts'],bundle:true,platform:'node',format:'esm',write:false});
const {createVehicleImpactDetector}=await import(`data:text/javascript;base64,${Buffer.from(result.outputFiles[0].contents).toString('base64')}`);
const detector=createVehicleImpactDetector();
const base={x:0,z:0,speed:8,verticalVelocity:0,driving:true};
assert.equal(detector.update(base,1/60),0);
assert.equal(detector.update({...base,x:0.1,verticalVelocity:0.01},1/60),0,'smooth motion is quiet');
assert.ok(detector.update({...base,x:0.2,verticalVelocity:0.5},1/60)>0,'suspension impulse triggers');
assert.equal(detector.update({...base,x:0.3,verticalVelocity:-0.5},1/60),0,'cooldown');
detector.reset();
assert.equal(detector.update(base,0.1),0);
assert.equal(detector.update({...base,x:200,verticalVelocity:5},0.1),0,'teleport suppression');
assert.equal(detector.update({...base,x:201,driving:false,verticalVelocity:-5},0.1),0,'on foot suppression');
detector.reset();detector.update(base,0.1);
assert.equal(detector.update({...base,speed:0,verticalVelocity:5},0.1),0,'stationary suppression');
assert.equal(detector.update({...base,verticalVelocity:NaN},0.1),0,'invalid telemetry clears history');
assert.equal(detector.update(base,0.1),0);
console.log('PASS suspension impacts: transient, smooth motion, cooldown, teleport, walking and invalid sample');
