import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { existsSync } from 'node:fs';
assert.ok(existsSync('src/vehicle/motorcycle-physics.ts'), 'missing motorcycle physics module');
const bundle = await build({ stdin: { contents: `export * from './src/vehicle/motorcycle-physics'; export * from './src/vehicle/index'; export * from './src/vehicle/catalog';`, resolveDir: process.cwd() }, bundle: true, platform: 'node', format: 'esm', write: false });
const api = await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].contents).toString('base64')}`);
const { NullEngine } = await import('@babylonjs/core/Engines/nullEngine.js');
const { Scene } = await import('@babylonjs/core/scene.js');
const flat = { heightAt: () => 0, normalAt: () => ({ x: 0, y: 1, z: 0 }) };
const input = { throttle: 1, steer: 0, handbrake: false, neutral: false };
const engine = new NullEngine(); const scene = new Scene(engine);
const legacy = api.createVehicle({ scene, terrain: flat, spawn: { x: 0, z: 0 } });
assert.equal(legacy.category, 'todoterreno');
assert.equal(legacy.root.getChildMeshes().find(m => m.name === 'vehicle:body-estandar')?.isEnabled(), true);
legacy.dispose();
for (const definition of api.VEHICLE_CATALOG.filter(d => d.category === 'moto')) {
  const p = definition.params;
  const s = api.createMotorcycleState(0, 0);
  for (let i = 0; i < 120; i++) api.stepMotorcycle(s, input, 1 / 60, p, flat);
  assert.ok(s.speed > 0, `${definition.id} throttle`);
  for (let i = 0; i < 60; i++) api.stepMotorcycle(s, { ...input, throttle: 0, steer: 0.12 }, 1 / 60, p, flat);
  assert.equal(s.fallen, false, 'stable turn');
  assert.equal(Math.sign(s.leanRad), Math.sign(s.yawRate), 'lean follows turn');
  s.leanRad = p.fallAngleRad + 0.1;
  api.stepMotorcycle(s, input, 1 / 60, p, flat);
  assert.equal(s.fallen, true);
  const location = [s.x, s.z];
  api.stepMotorcycle(s, input, 0.1, p, flat);
  assert.deepEqual([s.x, s.z], location, 'fallen throttle cannot move');
  const invalid = { ...flat, heightAt: () => NaN };
  assert.equal(api.recoverMotorcycle(s, p, invalid), false);
  const steep = { heightAt: (x) => x * 3, normalAt: () => ({ x: -3 / Math.sqrt(10), y: 1 / Math.sqrt(10), z: 0 }) };
  assert.equal(api.recoverMotorcycle(s, p, steep), false);
  assert.equal(api.recoverMotorcycle(s, p, flat), true);
  assert.deepEqual([s.x, s.z], location);
  assert.equal(s.fallen, false);
  const unstable = api.createMotorcycleState(0, 0);
  unstable.speed = p.maxSpeed;
  for (let i = 0; i < 120; i++) api.stepMotorcycle(unstable, { ...input, steer: 1 }, 1 / 60, p, flat);
  assert.equal(unstable.fallen, true, 'excess turn demand causes fall');
  const slope = { heightAt: (_x, z) => z * 0.2, normalAt: () => ({ x: 0, y: 1 / Math.hypot(1, 0.2), z: -0.2 / Math.hypot(1, 0.2) }) };
  const downhill = api.createMotorcycleState(0, 0);
  api.stepMotorcycle(downhill, { ...input, throttle: 0, neutral: true }, 0.1, p, slope);
  assert.ok(downhill.speed < 0, 'gravity on slope');
  const before = [scene.meshes.length, scene.materials.length, scene.transformNodes.length];
  const actor = api.createVehicle({ scene, terrain: slope, spawn: { x: 0, z: 0 } }, definition);
  assert.equal(actor.category, 'moto');
  assert.equal(actor.telemetry().contacts.length, 2);
  assert.equal(actor.contactPoints(actor.state).length, 2);
  assert.ok(actor.riderSeat && actor.cameraTarget, 'rider and camera anchors');
  assert.ok(actor.root.getChildMeshes().some(m => m.name.includes(`body-${definition.id}`)));
  actor.setInput(input); actor.step(0.05);
  assert.ok(actor.state.speed > 0);
  assert.ok(actor.applyPose() < 0.02, 'slope wheel support residual');
  actor.state.leanRad = p.fallAngleRad + 0.1; actor.step(0.02);
  assert.equal(actor.telemetry().fallen, true);
  assert.equal(actor.recover(), true);
  actor.dispose();
  assert.deepEqual([scene.meshes.length, scene.materials.length, scene.transformNodes.length], before, 'owned resources disposed');
  console.log(`PASS ${definition.id}: drive, turn, instability, recovery, slope, two contacts, anchors and disposal`);
}
scene.dispose(); engine.dispose();
console.log('PASS motorcycle and legacy factory overload');
